<a href="https://colab.research.google.com/github/ShelycaSurrayensih/PCVK_Genap_2022/blob/main/Challenge.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

# Matriks

matriksA = np.array([[0,-1,0],
                    [-1,5,-1],
                    [0,-1,0]])
matriksB = np.array([[-2,-1,0],
                      [-1,1,1],
                      [0,1,2]])   

perkalian_Skalar = matriksA*matriksB
perkalian_matriks1 = np.dot(matriksA,matriksB)
perkalian_matriks2 = matriksA.dot(matriksB)

print("Matriks A :")
print(matriksA)

print("Matriks B :")
print(matriksB)

print("Perkalian Skalar Matriks : ")
print(perkalian_Skalar)

print("Perkalian Matriks Cara 1 : ")
print(perkalian_matriks1)

print("Perkalian Matriks Cara 2 : ")
print(perkalian_matriks2)



Matriks A :
[[ 0 -1  0]
 [-1  5 -1]
 [ 0 -1  0]]
Matriks B :
[[-2 -1  0]
 [-1  1  1]
 [ 0  1  2]]
Perkalian Skalar Matriks : 
[[ 0  1  0]
 [ 1  5 -1]
 [ 0 -1  0]]
Perkalian Matriks Cara 1 : 
[[ 1 -1 -1]
 [-3  5  3]
 [ 1 -1 -1]]
Perkalian Matriks Cara 2 : 
[[ 1 -1 -1]
 [-3  5  3]
 [ 1 -1 -1]]


In [15]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [16]:
class DemoMatriks:  
    def __init__(self):
      # atur nilai matrix A dan matrix B
        self.matrix_A = np.array([[0,-1,0],
                                [-1,5,-1],
                                [0,-1,0]])
        self.matrix_B = np.array([[-2,-1,0],
                                  [-1,1,1],
                                  [0,1,2]])   
        
        # hitung ukuran baris dan kolom
        self.barMatA = len(self.matrix_A)    # jumlah baris A
        self.kolMatA = len(self.matrix_A[0]) # jumlah kolom A
        self.barMatB = len(self.matrix_B)    # jumlah baris B
        self.kolMatB = len(self.matrix_B[0]) # jumlah kolom B
 
        # buat matrix kosong --> hasil proses aritmatika
        self.buatMatrixHasil(self.barMatA, self.kolMatB)
 
        self.buatMenu()
         
    def buatMenu(self):
        Menu ="""
##########  PROGRAM ARITMATIKA MATRIKS  #######
     
Pilihan Metode Aritmatika:
<1> Perkalian Skalar
<2> Perkalian Matriks
<3> Image dikali matriks 3x3 
<4> Keluar
 
Silahkan Pilih Menu (1-4): """
 
        status = 0  # mati
        while not status:
            pilihan = input(Menu)
             
            print()
            print('Pilihan Anda: ', pilihan)
            print()
 
            if pilihan not in '1234':
                print('Pilihan Anda SALAH! Masukkan 1 - 4')
                print()
            else:
                if pilihan == '4':
                    status = 1  # hidup
                elif pilihan == '1':
                    self.kaliSkalar()
                elif pilihan == '2':
                    self.kaliMatrix()
                elif pilihan == '3':
                    self.imageMatrix()
                 
                 
    def buatMatrixHasil(self, baris, kolom):
        self.matrix_Hasil = []
        for i in range(baris):
            data = []
            for j in range(kolom):
                data.append(0)      # berisi data 0
            self.matrix_Hasil.append(data)
         
    def kaliSkalar(self):
        # proses perkalian Skalar
        for i in range(self.barMatA):
            for j in range(self.kolMatA):
                self.matrix_Hasil[i][j] = self.matrix_A[i][j] * self.matrix_B[i][j]
 
        print('Matrix A: ', self.matrix_A)
        print('Matrix B: ', self.matrix_B)
        print('Matrix A X B: ', self.matrix_Hasil)
                 
 
    def kaliMatrix(self):
        # proses perkalian Matrix
        for i in range(self.barMatA):
            for j in range(self.kolMatB):
                for k in range(self.barMatB):
                    self.matrix_Hasil= np.dot(self.matrix_A,self.matrix_B)
        print('Matrix A: ', self.matrix_A)
        print('Matrix B: ', self.matrix_B)
        print('Matrix A x B: ', self.matrix_Hasil)

    def imageMatrix(self):
        # proses image Matrix
        import matplotlib.image as image
        import numpy as np
        img=image.imread('/content/drive/MyDrive/PCVK_2022/Images/lena.jpg')
        print("Matriks : ")
        print(img)
 
 
if __name__ == '__main__':
    aplikasi = DemoMatriks()


##########  PROGRAM ARITMATIKA MATRIKS  #######
     
Pilihan Metode Aritmatika:
<1> Perkalian Skalar
<2> Perkalian Matriks
<3> Image dikali matriks 3x3 
<4> Keluar
 
Silahkan Pilih Menu (1-4): 1

Pilihan Anda:  1

Matrix A:  [[ 0 -1  0]
 [-1  5 -1]
 [ 0 -1  0]]
Matrix B:  [[-2 -1  0]
 [-1  1  1]
 [ 0  1  2]]
Matrix A X B:  [[0, 1, 0], [1, 5, -1], [0, -1, 0]]

##########  PROGRAM ARITMATIKA MATRIKS  #######
     
Pilihan Metode Aritmatika:
<1> Perkalian Skalar
<2> Perkalian Matriks
<3> Image dikali matriks 3x3 
<4> Keluar
 
Silahkan Pilih Menu (1-4): 2

Pilihan Anda:  2

Matrix A:  [[ 0 -1  0]
 [-1  5 -1]
 [ 0 -1  0]]
Matrix B:  [[-2 -1  0]
 [-1  1  1]
 [ 0  1  2]]
Matrix A x B:  [[ 1 -1 -1]
 [-3  5  3]
 [ 1 -1 -1]]

##########  PROGRAM ARITMATIKA MATRIKS  #######
     
Pilihan Metode Aritmatika:
<1> Perkalian Skalar
<2> Perkalian Matriks
<3> Image dikali matriks 3x3 
<4> Keluar
 
Silahkan Pilih Menu (1-4): 3

Pilihan Anda:  3

Matriks : 
[[[223 157 131]
  [222 157 129]
  [222 157 129